# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a46edb4eb437db8c42d0e43d383be9472fa34f35ad7fa84c151d6aaf094a666673d3992aa971506cb4603b17352d7bfab6ba0eda4a4057d449c87c1dc7025282

test:
  secret_key_base: bdc974b0a44d69fa21308eaf27f93a567bd585aa9ed43dc204241f989ba97ef568c443462d968a8c94ffc10f80761ee7540529408cdacfce763eab98ac4edc4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
